# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install knife
        run: |
          wget https://packages.chef.io/files/stable/chef-workstation/21.9.613/ubuntu/20.04/chef-workstation_21.9.613-1_amd64.deb
          sudo dpkg -i chef-workstation_21.9.613-1_amd64.deb

      - name: Spit out my IP address
        run: |
           echo +dig +short myip.opendns.com @resolver1.opendns.com;
           dig +short myip.opendns.com @resolver1.opendns.com

      # knife client create github
      - name: Write Chef Key
        env:
          CHEF_KEY: ${{ secrets.CHEF_KEY }}
        run: |
          echo Writing key file
          echo "$CHEF_KEY" > chef.pem

      # for cookbook in $(knife cookbook list | awk '{print $1}'); do knife acl add client github cookbooks $cookbook update ; done # add to existing cookbooks
      # knife acl add client github containers cookbooks update # add to future cookbooks
      # knife acl add client github containers sandboxes create
      - name: Upload Cookbook
        run: |
          echo Uploading cookbook
          knife cookbook upload ernie --key chef.pem --user github --server https://chef.ernie.org/organizations/ernie_org --cookbook-path ..
